#!/usr/bin/env python3
"""Convert saved .npy token files to MIDI/WAV for listening.

This script processes all .npy files generated by test_multi_conditioned.py
and converts them to MIDI and WAV format. This allows you to save disk space
during generation (only save .npy) and generate audio files later.

Usage:
    # Convert all .npy files in output directory
    python steering_interventions/dual_steering/convert_npy_to_audio.py \
        --input_dir steering_interventions/dual_steering_dp/outputs/phase4_conditioned
    
    # Convert only top N from listening list
    python steering_interventions/dual_steering/convert_npy_to_audio.py \
        --input_dir steering_interventions/dual_steering_dp/outputs/phase4_conditioned \
        --listening_list steering_interventions/dual_steering_dp/outputs/phase4_conditioned/listening_list.json \
        --top_n 20
    
    # Skip WAV generation (only MIDI)
    python steering_interventions/dual_steering/convert_npy_to_audio.py \
        --input_dir steering_interventions/dual_steering_dp/outputs/phase4_conditioned \
        --skip_wav
"""

import argparse
import json
import logging
import pathlib
import shutil
import sys
from typing import Optional

import numpy as np
from tqdm import tqdm

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent.parent / "mmt"))
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

import config
import representation


def convert_npy_to_audio(
    npy_file: pathlib.Path, encoding: dict, skip_wav: bool = False, force: bool = False
) -> bool:
    """Convert a single .npy file to MIDI/WAV.

    Args:
        npy_file: Path to .npy file
        encoding: Encoding dictionary
        skip_wav: If True, skip WAV generation (only MIDI)
        force: If True, overwrite existing files

    Returns:
        True if successful, False otherwise
    """
    try:
        midi_file = npy_file.with_suffix(".mid")
        wav_file = npy_file.with_suffix(".wav")

        # Check if already exists
        if not force:
            if midi_file.exists() and (skip_wav or wav_file.exists()):
                return True  # Already converted

        # Load tokens
        tokens = np.load(npy_file)

        # Decode to music
        music = representation.decode(tokens, encoding)

        # Save MIDI
        music.write(str(midi_file))

        # Save WAV (optional)
        if not skip_wav:
            music.write_audio(str(wav_file))

        return True

    except Exception as e:
        logging.error(f"Error converting {npy_file.name}: {e}")
        return False


def get_files_from_listening_list(
    listening_list_file: pathlib.Path,
    input_dir: pathlib.Path,
    top_n: Optional[int] = None,
    include_baselines: bool = True,
) -> list:
    """Get .npy file paths from listening list.

    Args:
        listening_list_file: Path to listening_list.json
        input_dir: Base input directory
        top_n: Only process top N examples (None = all)
        include_baselines: If True, also include baseline (α=0.0) files for comparison

    Returns:
        List of .npy file paths
    """
    with open(listening_list_file, "r") as f:
        data = json.load(f)

    examples = data["top_examples"]
    if top_n is not None:
        examples = examples[:top_n]

    npy_files = []
    baseline_files_added = set()  # Track baselines to avoid duplicates

    for example in examples:
        scenario = example["scenario"]
        strategy = example["strategy"]
        alpha_pitch = example["alpha_pitch"]
        alpha_duration = example["alpha_duration"]
        song_name = example["song_name"]

        # Add the steered version
        npy_path = (
            input_dir
            / scenario
            / strategy
            / f"ap{alpha_pitch:+.1f}_ad{alpha_duration:+.1f}"
            / f"{song_name}.npy"
        )

        if npy_path.exists():
            npy_files.append(npy_path)
        else:
            logging.warning(f"File not found: {npy_path}")

        # Add baseline version (α_pitch=0.0, α_duration=0.0) for comparison
        if include_baselines:
            baseline_key = (scenario, strategy, song_name)
            if baseline_key not in baseline_files_added:
                baseline_path = (
                    input_dir
                    / scenario
                    / strategy
                    / "ap+0.0_ad+0.0"
                    / f"{song_name}.npy"
                )

                if baseline_path.exists():
                    npy_files.append(baseline_path)
                    baseline_files_added.add(baseline_key)
                    logging.info(f"Added baseline for {song_name} in {scenario}")
                else:
                    logging.warning(f"Baseline not found: {baseline_path}")

    return npy_files


def copy_to_download_folder(
    listening_list_file: pathlib.Path,
    input_dir: pathlib.Path,
    output_folder: pathlib.Path,
    top_n: Optional[int] = None,
    skip_wav: bool = False,
    include_baselines: bool = True,
) -> None:
    """Copy converted files to a single folder with descriptive names.

    Args:
        listening_list_file: Path to listening_list.json
        input_dir: Base input directory with converted files
        output_folder: Destination folder for copies
        top_n: Only copy top N examples (None = all)
        skip_wav: If True, only copy MIDI files
        include_baselines: If True, also copy baseline files
    """
    with open(listening_list_file, "r") as f:
        data = json.load(f)

    examples = data["top_examples"]
    if top_n is not None:
        examples = examples[:top_n]

    output_folder.mkdir(parents=True, exist_ok=True)

    copied_count = 0
    baseline_files_copied = set()

    for i, example in enumerate(examples, 1):
        scenario = example["scenario"]
        strategy = example["strategy"]
        alpha_pitch = example["alpha_pitch"]
        alpha_duration = example["alpha_duration"]
        song_name = example["song_name"]

        # Shorten scenario name for filename
        scenario_short = scenario.replace("_", "")

        # Copy steered version
        base_path = (
            input_dir
            / scenario
            / strategy
            / f"ap{alpha_pitch:+.1f}_ad{alpha_duration:+.1f}"
            / song_name
        )

        # Copy MIDI
        midi_src = base_path.with_suffix(".mid")
        if midi_src.exists():
            midi_dst = (
                output_folder
                / f"{i:02d}_{song_name}_{scenario_short}_ap{alpha_pitch:+.1f}_ad{alpha_duration:+.1f}.mid"
            )
            shutil.copy(midi_src, midi_dst)
            copied_count += 1
        else:
            logging.warning(f"MIDI not found: {midi_src}")

        # Copy WAV
        if not skip_wav:
            wav_src = base_path.with_suffix(".wav")
            if wav_src.exists():
                wav_dst = (
                    output_folder
                    / f"{i:02d}_{song_name}_{scenario_short}_ap{alpha_pitch:+.1f}_ad{alpha_duration:+.1f}.wav"
                )
                shutil.copy(wav_src, wav_dst)
                copied_count += 1
            else:
                logging.warning(f"WAV not found: {wav_src}")

        # Copy baseline version
        if include_baselines:
            baseline_key = (scenario, strategy, song_name)
            if baseline_key not in baseline_files_copied:
                baseline_base_path = (
                    input_dir / scenario / strategy / "ap+0.0_ad+0.0" / song_name
                )

                # Copy baseline MIDI
                baseline_midi_src = baseline_base_path.with_suffix(".mid")
                if baseline_midi_src.exists():
                    baseline_midi_dst = (
                        output_folder / f"{song_name}_{scenario_short}_BASELINE.mid"
                    )
                    shutil.copy(baseline_midi_src, baseline_midi_dst)
                    copied_count += 1
                    baseline_files_copied.add(baseline_key)

                # Copy baseline WAV
                if not skip_wav:
                    baseline_wav_src = baseline_base_path.with_suffix(".wav")
                    if baseline_wav_src.exists():
                        baseline_wav_dst = (
                            output_folder / f"{song_name}_{scenario_short}_BASELINE.wav"
                        )
                        shutil.copy(baseline_wav_src, baseline_wav_dst)
                        copied_count += 1

    logging.info(f"Copied {copied_count} files to {output_folder}")


def main():
    parser = argparse.ArgumentParser(description="Convert .npy token files to MIDI/WAV")
    parser.add_argument(
        "--input_dir",
        type=pathlib.Path,
        required=True,
        help="Directory containing .npy files",
    )
    parser.add_argument(
        "--listening_list",
        type=pathlib.Path,
        default=None,
        help="Only convert files from listening_list.json",
    )
    parser.add_argument(
        "--top_n", type=int, default=None, help="Only convert top N from listening list"
    )
    parser.add_argument(
        "--skip_wav", action="store_true", help="Skip WAV generation (only MIDI)"
    )
    parser.add_argument(
        "--force", action="store_true", help="Overwrite existing MIDI/WAV files"
    )
    parser.add_argument(
        "--no_baselines",
        action="store_true",
        help="Skip baseline (α=0.0) files when using listening list",
    )
    parser.add_argument(
        "--output_folder",
        type=pathlib.Path,
        default=None,
        help="Copy all files to this folder with descriptive names for easy download",
    )

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
    )

    # Load encoding
    logging.info("Loading encoding...")
    encoding = representation.load_encoding(config.NOTES_DIR / "encoding.json")

    # Get list of files to convert
    if args.listening_list is not None:
        logging.info(f"Loading listening list from {args.listening_list}")
        npy_files = get_files_from_listening_list(
            args.listening_list,
            args.input_dir,
            args.top_n,
            include_baselines=not args.no_baselines,
        )
        logging.info(f"Found {len(npy_files)} files from listening list")
    else:
        # Find all .npy files recursively
        logging.info(f"Scanning {args.input_dir} for .npy files...")
        npy_files = list(args.input_dir.rglob("*.npy"))
        # Exclude cache file
        npy_files = [f for f in npy_files if "cache" not in f.name.lower()]
        logging.info(f"Found {len(npy_files)} .npy files")

    if len(npy_files) == 0:
        logging.error("No .npy files found!")
        return

    # Convert files
    logging.info("Converting files...")
    success_count = 0

    for npy_file in tqdm(npy_files, desc="Converting", unit="file"):
        if convert_npy_to_audio(npy_file, encoding, args.skip_wav, args.force):
            success_count += 1

    # Summary
    print("\n" + "=" * 60)
    print("Conversion complete!")
    print(f"  Successful: {success_count}/{len(npy_files)}")
    print(f"  Failed: {len(npy_files) - success_count}")
    if args.skip_wav:
        print("  Format: MIDI only")
    else:
        print("  Format: MIDI + WAV")
    print("=" * 60)

    # Copy to output folder if requested
    if args.output_folder and args.listening_list:
        logging.info(f"\nCopying files to {args.output_folder}...")
        copy_to_download_folder(
            args.listening_list,
            args.input_dir,
            args.output_folder,
            args.top_n,
            args.skip_wav,
            include_baselines=not args.no_baselines,
        )
        print(f"\n✅ Files ready for download in: {args.output_folder}")


if __name__ == "__main__":
    main()
