#!/usr/bin/env python3
"""Convert saved .npy token files to MIDI/WAV for listening.

Processes .npy files generated by test_dual_conditioned.py or
test_dual_unconditioned.py and converts them to MIDI + WAV format.

Usage:
    # Convert ALL .npy files in output directory
    python sparse_steering/dual_steering/convert_npy_to_audio.py \
        --input_dir exp/sod/sparse_steering/dual_steering/conditioned_ek2

    # Skip WAV (only produce MIDI — much faster)
    python sparse_steering/dual_steering/convert_npy_to_audio.py \
        --input_dir exp/sod/sparse_steering/dual_steering/conditioned_ek2 \
        --skip_wav

    # Convert a specific subdirectory
    python sparse_steering/dual_steering/convert_npy_to_audio.py \
        --input_dir exp/sod/sparse_steering/dual_steering/conditioned_ek2/low_pitch_short_duration_to_high_long
"""

import argparse
import logging
import pathlib
import sys

import numpy as np
from tqdm import tqdm

# Add mmt to path
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent.parent / "mmt"))
import representation


def convert_npy_to_audio(
    npy_file: pathlib.Path, encoding: dict, skip_wav: bool = False, force: bool = False
) -> bool:
    """Convert a single .npy file to MIDI and optionally WAV.

    Args:
        npy_file:  Path to .npy token file  (seq_len, 6)
        encoding:  MMT encoding dictionary
        skip_wav:  If True, only produce MIDI
        force:     If True, overwrite existing files

    Returns:
        True on success
    """
    try:
        midi_file = npy_file.with_suffix(".mid")
        wav_file = npy_file.with_suffix(".wav")

        # Skip if already converted
        if not force:
            if midi_file.exists() and (skip_wav or wav_file.exists()):
                return True

        tokens = np.load(npy_file)
        music = representation.decode(tokens, encoding)

        music.write(str(midi_file))

        if not skip_wav:
            music.write_audio(str(wav_file))

        return True

    except Exception as e:
        logging.error(f"Error converting {npy_file.name}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Convert .npy token files to MIDI/WAV")
    parser.add_argument(
        "--input_dir",
        type=pathlib.Path,
        required=True,
        help="Directory (recursive) containing .npy files",
    )
    parser.add_argument(
        "--skip_wav",
        action="store_true",
        help="Only produce MIDI files (skip WAV — much faster)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing MIDI/WAV files",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
    )

    # Load encoding
    encoding_path = (
        pathlib.Path(__file__).parent.parent.parent
        / "data"
        / "sod"
        / "processed"
        / "notes"
        / "encoding.json"
    )
    logging.info(f"Loading encoding from {encoding_path}")
    encoding = representation.load_encoding(str(encoding_path))

    # Discover .npy files
    npy_files = sorted(args.input_dir.rglob("*.npy"))
    # Exclude cache / results files
    npy_files = [f for f in npy_files if "cache" not in f.name.lower()]
    logging.info(f"Found {len(npy_files)} .npy files in {args.input_dir}")

    if not npy_files:
        logging.error("No .npy files found!")
        return

    success = 0
    for npy_file in tqdm(npy_files, desc="Converting", unit="file"):
        if convert_npy_to_audio(npy_file, encoding, args.skip_wav, args.force):
            success += 1

    print(f"\nDone: {success}/{len(npy_files)} converted successfully")
    if args.skip_wav:
        print("  Format: MIDI only")
    else:
        print("  Format: MIDI + WAV")


if __name__ == "__main__":
    main()
